<a href="https://colab.research.google.com/github/RAPARLAPRASANNAKUMAR/BTECH/blob/main/SentimentAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:

import pandas as pd
import numpy as np
import nltk
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import string
from nltk.corpus import stopwords

# Download NLTK resources (if not already installed)
nltk.download('stopwords')
nltk.download('punkt')


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [34]:

# Load the dataset
train_path = "/content/drive/MyDrive/TwitterData/TwitterData/twitter_training.csv"
valid_path = "/content/drive/MyDrive/TwitterData/TwitterData/twitter_validation.csv"

df_train = pd.read_csv(train_path, header=None)
df_valid = pd.read_csv(valid_path, header=None)

# Display first few rows of training data
df_train.head()


0            1         2  \
0  2401  Borderlands  Positive   
1  2401  Borderlands  Positive   
2  2401  Borderlands  Positive   
3  2401  Borderlands  Positive   
4  2401  Borderlands  Positive   

                                                   3  
0  im getting on borderlands and i will murder yo...  
1  I am coming to the borders and I will kill you...  
2  im getting on borderlands and i will kill you ...  
3  im coming on borderlands and i will murder you...  
4  im getting on borderlands 2 and i will murder ...

In [35]:

# Assign column names (based on sample dataset structure)
df_train.columns = ['ID', 'Entity', 'Sentiment', 'Text']
df_valid.columns = ['ID', 'Entity', 'Sentiment', 'Text']

# Keep only relevant columns
df_train = df_train[['Text', 'Sentiment']]
df_valid = df_valid[['Text', 'Sentiment']]

# Display dataset info
df_train.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74682 entries, 0 to 74681
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   Text       73996 non-null  object
 1   Sentiment  74682 non-null  object
dtypes: object(2)
memory usage: 1.1+ MB


In [36]:

def preprocess_text(text):
    text = str(text).lower()  # Convert text to lowercase
    text = ''.join([char for char in text if char not in string.punctuation])  # Remove punctuation
    stop_words = set(stopwords.words('english'))  # Stopwords set
    words = text.split()
    words = [word for word in words if word not in stop_words]  # Remove stopwords
    return ' '.join(words)

# Apply the preprocessing function to training and validation text data
df_train['Text'] = df_train['Text'].apply(preprocess_text)
df_valid['Text'] = df_valid['Text'].apply(preprocess_text)

# Display first few rows after preprocessing
df_train.head()


Text Sentiment
0    im getting borderlands murder  Positive
1              coming borders kill  Positive
2      im getting borderlands kill  Positive
3     im coming borderlands murder  Positive
4  im getting borderlands 2 murder  Positive

In [37]:

vectorizer = TfidfVectorizer()
X_train = vectorizer.fit_transform(df_train['Text'])
X_valid = vectorizer.transform(df_valid['Text'])

y_train = df_train['Sentiment']
y_valid = df_valid['Sentiment']


In [38]:

model = LogisticRegression(max_iter=500)
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_valid)

# Evaluate the model
accuracy = accuracy_score(y_valid, y_pred)
conf_matrix = confusion_matrix(y_valid, y_pred)
report = classification_report(y_valid, y_pred)

# Print results
print(f"Accuracy: {accuracy * 100:.2f}%")
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", report)


Accuracy: 92.30%
Confusion Matrix:
 [[159   6   2   5]
 [  4 252   4   6]
 [  2  18 256   9]
 [  8   9   4 256]]
Classification Report:
               precision    recall  f1-score   support

  Irrelevant       0.92      0.92      0.92       172
    Negative       0.88      0.95      0.91       266
     Neutral       0.96      0.90      0.93       285
    Positive       0.93      0.92      0.93       277

    accuracy                           0.92      1000
   macro avg       0.92      0.92      0.92      1000
weighted avg       0.92      0.92      0.92      1000

